name: CI

on:
  push:
    branches: ['*']
  pull_request:

jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7

      - uses: actions/setup-go@v6
        with:
          go-version-file: go.mod

      - name: Vet
        run: go vet ./...

      - name: Lint
        uses: golangci/golangci-lint-action@v9
        with:
          version: v2.11.4

      - name: Test
        run: go test ./... -count=1 -race

      - name: Build
        run: go build ./cmd/sophosfw
